jc-522
saritasa-nest/camp-js-2023-egor-ryazanov pull request #1
Opened 2023-07-06 05:29 UTC by EgorRyazanov

2023-07-06 11:40 UTC, artem-sotnichenko-saritasa requested changes
Great job so far!
Replay the comments if something isn't clear for you. And If something is especially tricky, don't be shy to write me in slack!

2023-07-06 11:40 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/pages/1/css/base.css
> +  justify-content: center;
`justify-content` works only with flex(`display: flex`). So you can remove it.

2023-07-06 11:40 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/pages/1/css/components.css
> +  background-color: white;
As a rule of thumb, please extract colors into variables.
In real project, if we would want to change background color from white, it will be tiresome to go change it everywhere.

2023-07-06 11:40 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/pages/1/css/components.css
> +  border-radius: 24px;
Please extract `border-radius` into variable too

2023-07-06 11:40 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/pages/1/css/components.css
> +  height: 224px;
The height of the filters block should be calculated depending on the content inside. I mean that filters shouldn't have `height` css rule.

2023-07-06 11:40 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/pages/1/css/components.css
> +  background: url("../images/icons/search.svg") no-repeat 16px;
I believe you can write it:
`background: var(--surface-overlay) url("../images/icons/search.svg") no-repeat 16px;`
But I suggest not using shorthand syntax, because it's can be not obvious what each property means.

2023-07-06 11:40 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/pages/1/css/components.css
> +  color: black;
Please extract it into variable

2023-07-06 11:40 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/pages/1/css/media.css
> +  }
Instead of `margin` please use flexbox. The `flex-wrap: wrap` rule should help you here.

2023-07-06 11:40 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/pages/1/css/variables.css
> +  --border: rgb(0 0 0 / 15%);
Please add `color` suffix. We can have different types of variables, it would help easly distinguish them

2023-07-06 11:40 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/pages/1/index.html
> +                      <source srcset="./images/2020/1/1-148px.png" media="(max-width: 552px)" />
Please be consistent with using tabs

2023-07-06 11:40 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/pages/1/index.html
> +										<h4 class="card__title body--small">Learning JavaScript Design Patterns</h4>
Ideally, `alt` should explain what's on the image. In this case it could be "Book cover with bird on white background". 
But usually it's unreal. So I suggest leaving alt empty `alt=""` because people using screen reader won't benefit from bad alt text.

2023-07-06 11:40 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/pages/1/css/media.css
> +  }
Actually, as a rule of thumb, you shouldn't use `margin` at all. 
Because usually you want the parent to control how children are placed. So `.filtered-cards` can easily change behavior how cards are placed, without changing `.filtered-cards__item` code.

2023-07-06 11:57 UTC, pavel-romanov8 requested changes
I noticed next problems with current implementation:

- There is some gap when I try to scroll down the page. The part of content is visible because of that
<img width="536" alt="Screenshot 2023-07-06 at 17 40 25" src="https://github.com/saritasa-nest/camp-js-2023-egor-ryazanov/assets/82144989/b798f115-efdf-4327-8541-38befe129f75">

- Filters section taks half of my screen on small screen sizes. Is it possible to improve?
<img width="215" alt="Screenshot 2023-07-06 at 17 43 13" src="https://github.com/saritasa-nest/camp-js-2023-egor-ryazanov/assets/82144989/c87972d7-968a-4fd1-bb97-f6d13cf0eaa0">
618f">

P.S. I tested it in Safari

2023-07-06 11:57 UTC, pavel-romanov8 commented on apps/vanilla/src/pages/1/css/base.css
> +@import url("https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap");
Would be great to load fonts via `link` HTML tag instead. The main difference is speed of fields loading. With current implementation, it goes like this:
1. Load HTLM (in all browsers)
2. Load CSS (in most of the browsers)

It means that your fonts will be available only browser loads this CSS file. With `link` we can start loading them on first step

2023-07-06 11:57 UTC, pavel-romanov8 commented on apps/vanilla/src/pages/1/css/base.css
> +  font-weight: 400;
Default `fontWeight` value equals to `400`, so there is no need to declare it explicitly

2023-07-06 11:57 UTC, pavel-romanov8 commented on apps/vanilla/src/pages/1/css/base.css
> +  font-size: 400;
It is pretty confusing to see font size set as a plain number. Usually we use some units for it

2023-07-06 11:57 UTC, pavel-romanov8 commented on apps/vanilla/src/pages/1/css/base.css
> +}
This file looks like an extension of `normalize.css` styles. Instead of creating a separate one, I would probably put it into `normalize.css`

2023-07-06 11:57 UTC, pavel-romanov8 commented on apps/vanilla/src/pages/1/css/components.css
> +.logo {
If these are styles that you are planning to reuse across the app we can move them in a separate file since they are mixed with some specific one it is hard to track them

2023-07-06 11:57 UTC, pavel-romanov8 commented on apps/vanilla/src/pages/1/css/components.css
> +  text-transform: uppercase;
Would be great to have separate file with typography-related classes only

2023-07-06 11:57 UTC, pavel-romanov8 commented on apps/vanilla/src/pages/1/css/components.css
> +  height: 306.8px;
It is not required to have pixel perfect result, therefore there is no need to use such values. They only bring more confusion

2023-07-06 11:57 UTC, pavel-romanov8 commented on apps/vanilla/src/pages/1/css/components.css
> +  background-color: white;
Let's extract all colors-related values into variables. That way, we can preserve consistent colors across the site

2023-07-06 11:57 UTC, pavel-romanov8 commented on apps/vanilla/src/pages/1/css/media.css
> +@media screen and (max-width: 1280px) {
The downside of placing media in a separate file is that I have to switch between these 2 in order to establish the entire logic flow

2023-07-06 11:57 UTC, pavel-romanov8 commented on apps/vanilla/src/pages/1/css/media.css
> +  .container {
I would be very careful in changing utility classes in such cases, since it is possible to non-intentionally break other places

2023-07-06 11:57 UTC, pavel-romanov8 commented on apps/vanilla/src/pages/1/css/media.css
> +  .filtered-cards__item:nth-child(4n) {
You can avoid the headache with margin management by using flex/grid layout. Instead of managing them by hands, we can use gaps and other properties

How it looks now:
<img width="380" alt="Screenshot 2023-07-06 at 17 52 07" src="https://github.com/saritasa-nest/camp-js-2023-egor-ryazanov/assets/82144989/8ff7eb61-f7da-4eb5-8432-fa90e9ff2153">

2023-07-07 03:52 UTC, SofyaKirillova commented on apps/vanilla/src/pages/1/css/components.css
> +.body {
You aren't using the `body` class. Maybe you meant the `body` tag?

2023-07-07 03:52 UTC, SofyaKirillova commented on apps/vanilla/src/pages/1/css/media.css
> +  .filtered-cards__card .card__title {
Exactly the same parameters are available in the components.css file

2023-07-07 03:52 UTC, SofyaKirillova commented on apps/vanilla/src/pages/1/index.html
> +                      <source srcset="./images/2020/1/1-148px.png" media="(max-width: 552px)" />
Check it in the whole file

2023-07-07 03:52 UTC, SofyaKirillova commented on apps/vanilla/src/pages/1/images/1980/1/1-148px.png
I think it's better to use `object-fit` so as not to store 2 identical images

2023-07-07 08:49 UTC, EgorRyazanov commented on apps/vanilla/src/pages/1/css/components.css
> +  border-radius: 24px;
i think there's no point to use variable. I have used this value only one time

2023-07-07 08:54 UTC, EgorRyazanov commented on apps/vanilla/src/pages/1/css/media.css
> +  .container {
Can you please explain what do you mean? I thought it's normal practice to change the size of container and produce adaptive things based on it. At least, I think this approach is appropriate for small projects. Initially, I thought through the logic based on this possibility, and does it make sense to change everything in this case?

2023-07-07 08:55 UTC, EgorRyazanov commented on apps/vanilla/src/pages/1/images/1980/1/1-148px.png
I see advantages in each approach. The designer has different pictures for different sizes, do I still need to change this functionality, or can I leave everything as it is for now and take this remark into account in the future?

2023-07-07 09:27 UTC, SofyaKirillova commented on apps/vanilla/src/pages/1/images/1980/1/1-148px.png
If the images use different ways of resizing then you can leave it as it is but in the future it is better to use `object-fit`

2023-07-10 08:13 UTC, golovachev-yaroslav approved these changes

2023-07-10 10:05 UTC, pavel-romanov8 commented on apps/vanilla/src/pages/1/css/components.css
> +.filter__form .form__element {
Do you really need to target `form__element` with extra `filter__form` class? It looks redundant and creates boilerplate code

2023-07-10 10:07 UTC, pavel-romanov8 commented on apps/vanilla/src/pages/1/css/components.css
> +  margin-bottom: 0;
Is it possible to use gaps in flex/grid layouts to avoid doing such things?

2023-07-10 10:32 UTC, pavel-romanov8 commented on apps/vanilla/src/pages/1/css/components.css
> +  color: var(--primary-contrast-color);
Please, review styles for the focus element. I have some noises on Safari
<img width="430" alt="Screenshot 2023-07-10 at 16 31 15" src="https://github.com/saritasa-nest/camp-js-2023-egor-ryazanov/assets/82144989/8cabf2a6-0621-48cf-8295-e216bde2758d">

2023-07-10 10:36 UTC, pavel-romanov8 commented on apps/vanilla/src/pages/1/css/components.css
> +    width: 312px;
Not sure why is it required to change container with for every query. Can we keep 100% for width after some value and provide additional margin instead? P.S. we can use `min` or `max` CSS functions for it

2023-07-10 10:39 UTC, pavel-romanov8 commented on apps/vanilla/src/pages/1/css/components.css
> +    top: 132px;
Is it required to set top explicitly? Sticky elements, unlike the absolute one doesn't fly off the document structure, therefore we can rely on it

2023-07-10 10:40 UTC, pavel-romanov8 commented on apps/vanilla/src/pages/1/css/components.css
> +    top: 0;
We still have the problem of half screen filters on mobile. I would remove filters from sticky group and leave them as the top of the page
<img width="154" alt="Screenshot 2023-07-10 at 15 53 34" src="https://github.com/saritasa-nest/camp-js-2023-egor-ryazanov/assets/82144989/087167bd-6775-44c2-a5b7-0c7ad51820c2">

2023-07-10 10:42 UTC, pavel-romanov8 commented on apps/vanilla/src/pages/1/images/icons/arrow.svg
> +<path id="Vector" d="M19.5 8.25L12 15.75L4.5 8.25" stroke="black" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
In order to reduce size of shipped app size to the users, we prefer using [this](https://jakearchibald.github.io/svgomg/) service for SVGs. It helps to reduce their size

2023-07-10 10:43 UTC, pavel-romanov8 commented on apps/vanilla/src/pages/1/index.html
> +		<div class="container header__container">
This `div` looks redundant. Can we do everything we want just with `header` and `h2` inside of it?

2023-07-10 12:45 UTC, EgorRyazanov commented on apps/vanilla/src/pages/1/css/components.css
> +    top: 132px;
Yea, i think, it's required because we have 2 sticky elements and they gonna stack

2023-07-10 12:46 UTC, EgorRyazanov commented on apps/vanilla/src/pages/1/css/components.css
> +    top: 0;
![image](https://github.com/saritasa-nest/camp-js-2023-egor-ryazanov/assets/89483642/d2a49d42-1443-4ee5-bb4f-592cf59503a7)

2023-07-10 12:49 UTC, EgorRyazanov commented on apps/vanilla/src/pages/1/css/components.css
> +  color: var(--primary-contrast-color);
I dont sure, but i think problem is gone

2023-07-11 05:24 UTC, pavel-romanov8 approved these changes

2023-07-11 05:24 UTC, pavel-romanov8 commented on apps/vanilla/src/pages/1/css/components.css
> +  color: var(--primary-contrast-color);
It is still presented in Safari. You can skip this bug, since it is only related to 1 browser, if you don't have time to fix it. However, it might be a good experience of troubleshooting browser-specific bugs

2023-07-11 05:24 UTC, pavel-romanov8 commented on apps/vanilla/src/pages/1/css/components.css
> +    top: 0;
Looks like we can omit declaration of `top` property here, since it is set to `0` initially

2023-07-11 07:47 UTC, artem-sotnichenko-saritasa approved these changes

2023-07-11 08:59 UTC, merged

2023-07-11 09:00 UTC, irina-baleevskih-saritasa commented on apps/vanilla/src/pages/1/index.html
> +										<h4 class="card__title body_small">Refactoring UI</h4>
Are you using this class?

2023-07-11 09:00 UTC, irina-baleevskih-saritasa commented on apps/vanilla/src/pages/1/css/components.css
> +  text-overflow: ellipsis;
Please check that this property is working.

2023-07-11 09:00 UTC, irina-baleevskih-saritasa commented on apps/vanilla/src/pages/1/index.html
> +									<div class="card__body">
You can omit this container

2023-07-11 09:00 UTC, irina-baleevskih-saritasa commented on apps/vanilla/src/pages/1/css/components.css
> +  gap: 24px 0;
```suggestion
  gap: 24px;
```