Feature/jc 540 anime app table view
saritasa-nest/camp-js-2023-egor-ryazanov pull request #4
Opened 2023-07-21 04:20 UTC by EgorRyazanov

2023-07-23 11:47 UTC, dmitrymaslov13 requested changes

2023-07-23 11:47 UTC, dmitrymaslov13 commented on libs/core/utils/types.ts
> +export enum Type {
I think we should make them more descriptive. For example: `AnimeType`, `AnimeStatus`, `AnimeRating`

2023-07-23 11:47 UTC, dmitrymaslov13 commented on libs/core/utils/types.ts
> +	'UNKNOWN',
let's improve this:
```suggestion
	TV = 'TV',
	OVA = 'OVA',
	Movie = 'MOVIE',
	Special = 'SPECIAL',
	ONA = 'ONA',
	Music = 'MUSIC',
	Unknown = 'UNKNOWN',
```

'Why?' you can ask me: 
- The fact is that even if the enum values somehow change, we will not have to change anything in the application.
- Regardless of the values, we will be able to control the naming in our application.

2023-07-23 11:47 UTC, dmitrymaslov13 commented on libs/core/utils/types.ts
let's put these types in a separate more descriptive file, or in a file with an anime model.

and learn the next point, enum also needs to be mapped to the domain layer, we discussed this in another review, you can read it here: 

https://github.com/saritasa-nest/camp-js-2023-irina-tumanova/pull/5#discussion_r1268104142

2023-07-23 11:47 UTC, dmitrymaslov13 commented on apps/angular/src/app/features/anime-page/anime-page.module.ts
> +export class AnimePageModule {}
I think is `AnimeModule` and not `AnimePageModule`
Let's rename

2023-07-23 11:47 UTC, dmitrymaslov13 commented on apps/angular/src/app/features/anime-page/anime-page.module.ts
> +import { CommonModule, NgIf } from '@angular/common';
`NgIf` module is included in `CommonModule`

https://angular.io/api/common/NgIf#exported-from

2023-07-23 11:47 UTC, dmitrymaslov13 commented on apps/angular/src/core/interceptors/base-headers.interceptor.ts
> +			headers: request.headers.set('Content-Type', 'application/json'),
are you sure this value is not the default value?

2023-07-23 11:47 UTC, dmitrymaslov13 commented on apps/angular/src/shared/components/spinner/spinner.component.css
> +  width: 100vw;
be careful, the dimension of this spinner is in the entire browser screen, did you really mean it that way?

2023-07-23 11:47 UTC, dmitrymaslov13 commented on apps/angular/src/shared/shared.module.ts
> +import { HttpClientModule } from '@angular/common/http';
```suggestion
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { HttpClientModule } from '@angular/common/http';
```

2023-07-23 11:47 UTC, dmitrymaslov13 commented on apps/angular/src/theme/values.css
Let's rename file to 'variables.css'

2023-07-23 11:47 UTC, dmitrymaslov13 commented on libs/core/dtos/anime-params.dto.ts
> +export interface AnimeParametersDto {
Wow brooo! Are you really going to use all those fields?
This sounds incredibly exciting! :D 

But seriously, you don’t need to add those parameters that you don’t use, so you create more work for yourself and potential places for errors to appear in the code

2023-07-23 11:47 UTC, dmitrymaslov13 commented on apps/angular/src/core/utils/create-http-params.ts
> +export function createHttpParams(params: { [key in string]: any }): HttpParams {
Oh my friend)) It's overhead: 

If you check [HttpParams documentation](https://angular.io/api/common/http/HttpParams), you can see that the angular has already thought of everything, the class constructor takes a [convenient object for create HtppParams](https://angular.io/api/common/http/HttpParamsOptions)

2023-07-23 11:47 UTC, dmitrymaslov13 commented on apps/angular/src/core/utils/constants.ts
> +export const LIMIT_ITEMS = 25;
I think it not global constant, it's default param for get anime items

2023-07-23 11:47 UTC, dmitrymaslov13 commented on apps/angular/src/app/features/anime-page/anime-page.component.ts
> +	public animeResponse$ = new Observable<AnimePagination>();
you don't need to indicate that this is some kind of answer. on the UI layer, you know that this is an anime sheet and that's it. let's rename

`animeList$` | `paginatedAnime$` | ...

2023-07-23 11:47 UTC, dmitrymaslov13 commented on apps/angular/src/app/features/anime-page/anime-page.component.ts
> +	public animeResponse$ = new Observable<AnimePagination>();
Why you declare instance? Please add only type
```suggestion
	public readonly animeResponse$: Observable<AnimePagination>;
```

And please not forget about readonly

2023-07-23 11:47 UTC, dmitrymaslov13 commented on apps/angular/src/app/features/anime-page/anime-page.component.ts
> +	public page$ = new BehaviorSubject<number>(0);
readonly

2023-07-23 11:47 UTC, dmitrymaslov13 commented on apps/angular/src/app/features/anime-page/anime-page.component.ts
> +	public isLoading$ = new BehaviorSubject<boolean>(false);
readonly

2023-07-23 11:47 UTC, dmitrymaslov13 commented on apps/angular/src/app/features/anime-page/anime-page.component.ts
> +	public getNextPage(pageEvent?: PageEvent): void {
the name of the method is misleading, you don't get any data, let's rename it!
`setPage` for example

2023-07-23 11:47 UTC, dmitrymaslov13 commented on apps/angular/src/app/features/anime-page/anime-page.component.ts
> +	public animeResponse$ = new Observable<AnimePagination>();
And if your class not abstract, or you not create hard logic with interaction with its fields and methods from another class, to work in the template, it is enough to make the fields `protected`.
The same goes for methods!

2023-07-23 11:47 UTC, dmitrymaslov13 commented on apps/angular/src/app/features/anime-page/anime-page.component.ts
> +	public createAnimesStream(): Observable<AnimePagination> {
```suggestion
	private createAnimesStream(): Observable<AnimePagination> {
```

2023-07-23 11:47 UTC, dmitrymaslov13 commented on libs/core/mappers/anime.mapper.ts
> +	export function fromAnimePaginationDto(dto: AnimePaginationDto): AnimePagination {
I think that pagination data will obviously be used not only for anime. Let's create a separate pagination parameter mapper that will accept a mapper for elements.

```ts
fromPaginatedDto(PaginatedAnimeDto, AnimeMapper.fromAnimeDto)
```

2023-07-23 11:47 UTC, dmitrymaslov13 commented on apps/angular/src/core/services/anime.service.ts
> +			.get<AnimePaginationDto>(new URL(this.animePathname, environment.baseUrl).href, {
```suggestion
			.get<AnimePaginationDto>(new URL(this.animePathname, environment.baseUrl).toString(), {
```

2023-07-23 11:53 UTC, dmitrymaslov13 requested changes

2023-07-23 11:53 UTC, dmitrymaslov13 commented on apps/angular/src/app/features/anime-page/anime-page.component.html
> +		[length]="animeResponse.count / 25"
What is `25`, what is this magic number?

so that there are no such questions, the numbers must be taken out into a variable

looks like it shouldn't be here at all

2023-07-23 11:53 UTC, dmitrymaslov13 commented on apps/angular/src/app/features/anime-page/anime-page.component.html
> +		[pageSize]="1"
Also about magic number. looks very strange

2023-07-23 11:53 UTC, dmitrymaslov13 commented on apps/angular/src/app/features/anime-page/anime-page.component.html
> +		[length]="animeResponse.count / 25"
I’ll also add that you shouldn’t do any calculations in the template at all. Usually they are best done at the typescript level.

2023-07-23 11:53 UTC, dmitrymaslov13 commented on apps/angular/src/app/features/anime-page/anime-page.component.html
> +				<img alt="{{ anime.titleEnglish }}" class="anime__image" src="{{ anime.image }}" />
```suggestion
				<img class="anime__image" [alt]="anime.titleEnglish" [src]="anime.image" />
```

2023-07-24 04:02 UTC, pavel-romanov8 requested changes

2023-07-24 04:02 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime/anime-page/anime-page.component.html
> +<camp-spinner *ngIf="isLoading$ | async"></camp-spinner>
We can leverage self-closing tags
```suggestion
<camp-spinner *ngIf="isLoading$ | async" />
```

2023-07-24 04:02 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime/anime-page/anime-page.component.ts
> +			shareReplay({ refCount: true, bufferSize: 1 }),
Why do you need to multicast the observable? From what I see, you are subscribing to it only once

2023-07-24 04:02 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime/anime-page/anime-page.component.ts
> +		return Math.ceil(animeCount / this.limitPageItems);
The same thing with abstraction leaks. It shouldn't be placed it component. Try to encapsulate it in pagination class

2023-07-24 04:02 UTC, pavel-romanov8 commented on apps/angular/src/core/interceptors/api-key.interceptor.ts
> +/** Api Key Interceptor. */
```suggestion
/** API key interceptor. */
```

2023-07-24 04:02 UTC, pavel-romanov8 commented on apps/angular/src/core/services/anime.service.ts
> +/** Anime Service. */
```suggestion
/** Anime service. */
```

2023-07-24 05:20 UTC, dmitrymaslov13 commented on libs/core/dtos/anime.dto.ts
>  	/** Id. */
```suggestion
	/** ID. */
```

2023-07-24 06:48 UTC, EgorRyazanov commented on apps/angular/src/app/features/anime/anime-page/anime-page.component.ts
> +			}),
in this case prettier and editor config with project settings changes it.

2023-07-24 06:52 UTC, EgorRyazanov commented on apps/angular/src/app/features/anime/anime-page/anime-page.component.ts
> +	/** Status of anime getting from server. */
Fixed abstraction leak. But the loading status remains in the same position, because at the moment I don't need this functionality and complexity

2023-07-24 10:12 UTC, kristinaSvobodinaSaritasa commented on apps/angular/src/app/features/anime/anime-page/anime-page.component.ts
> +export class AnimePageComponent {
For me, naming `anime-page `means page about one anime not a list of anime, could you improve naming please.

2023-07-24 10:12 UTC, kristinaSvobodinaSaritasa commented on apps/angular/src/app/features/anime/anime-page/anime-page.component.ts
> +			this.pageSize$.next(pageEvent.pageIndex);
Seems like it should be `pageNumber$`,isn't it?

2023-07-24 10:12 UTC, kristinaSvobodinaSaritasa commented on apps/angular/src/core/services/url.service.ts
> +	public generateURI(pathname: URL | string): string {
Maybe `generateURL` ?

2023-07-25 00:53 UTC, kristinaSvobodinaSaritasa commented on apps/angular/src/app/features/anime/animes-page/animes-page.component.ts
>  	selector: 'camp-anime-page',
I think the selector also needs to be changed.

2023-07-25 23:00 UTC, dmitrymaslov13 requested changes

2023-07-25 23:00 UTC, dmitrymaslov13 commented on apps/angular/src/core/utils/create-http-params.ts
> +export function createHttpParams(params: { [key in string]: any }): HttpParams {
Please tell me what problem this method solves

Why you not use?
```ts
new HttpParams({
  fromObject: {...objectWithYourParams}
})
```

2023-07-26 14:01 UTC, dmitrymaslov13 approved these changes

2023-07-26 14:07 UTC, dmitrymaslov13 commented on apps/angular/src/app/features/anime/animes-page/animes-page.component.html
> +				<td mat-cell *matCellDef="let anime">{{ anime.status }}</td>
usually we display enum values directly in the template, and create an abstraction for this. This is done because the enum value is not necessarily the text that we want to see in the template, and for the flexibility to change it if necessary.

look at the example I described and let's improve it

```ts
export enum BidLead {
  BuildingOwner = 'BuildingOwner',
  BuildersExchange = 'BuildersExchange',
  ConstructionDatabase = 'ConstructionDatabase',
  Consultants = 'Consultants',
}

export namespace BidLead {
  const TO_TITLE_MAP: Record<BidLead, string> = {
    [BidLead.BuildingOwner]: 'Building Owner',
    [BidLead.BuildersExchange]: 'Builders Exchange',
    [BidLead.ConstructionDatabase]: 'Construction Database',
    [BidLead.Consultants]: 'Consultants',
  };

  /**
   * Converts a certain bid lead to readable title.
   * @param value Bid lead.
   */
  export function toReadable(value: BidLead): string {
    return TO_TITLE_MAP[value];
  }
}
```

2023-07-26 14:11 UTC, dmitrymaslov13 commented on apps/angular/src/core/services/anime.service.ts
> +	public constructor() {}
You can remove empty constructor

2023-07-27 06:32 UTC, dmitrymaslov13 commented on apps/angular/src/app/features/anime/animes-page/animes-page.component.html
> +			class="table"
Just FYI:

there is a practice of attribute order, it improves readability
https://github.com/Gbuomprisco/opinionated-angular#rules-for-writing-html-tags

Also Angular eslint have this rule in config, if interesting i can send you

2023-07-27 07:49 UTC, pavel-romanov8 approved these changes

2023-07-27 07:49 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime/animes-page/animes-page.component.ts
> +		return anime.id.toString();
Is there any profit of string over original ID type?

2023-07-27 07:49 UTC, pavel-romanov8 commented on apps/angular/src/index.html
> +</head>
Looks like indentations are off here

2023-07-27 07:49 UTC, pavel-romanov8 commented on apps/angular/src/shared/components/spinner/spinner.component.html
> +<mat-spinner [color]="'accent'"></mat-spinner>
Can we use self-closing tag?

2023-07-27 07:49 UTC, pavel-romanov8 commented on libs/core/mappers/anime.mapper.ts
> +	export function fromAnimeDto(dto: AnimeDto): Anime {
We can unify naming for each mapper functions since they will be the same
```suggestion
	export function fromDto(dto: AnimeDto): Anime {
```

2023-07-27 07:49 UTC, pavel-romanov8 commented on libs/core/mappers/anime.mapper.ts
> +	 * @param dto Anime GTO.
```suggestion
	 * @param dto Anime DTO.
```

2023-07-27 07:49 UTC, pavel-romanov8 commented on libs/core/models/anime-params.ts
> +export class AnimeParameters extends Immerable {
Not sure why do we need class here? Will simple type work for us?

2023-07-27 09:47 UTC, merged