Feature/jc 546 anime list managment
saritasa-nest/camp-js-2023-egor-ryazanov pull request #5
Opened 2023-07-27 13:09 UTC by EgorRyazanov

2023-07-28 02:57 UTC, pavel-romanov8 requested changes

2023-07-28 02:57 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime/animes-page/animes-page.component.html
> +		<mat-form-field color="accent" class="form__field">
Looks like you are not using it
```suggestion
		<mat-form-field color="accent">
```

2023-07-28 02:57 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime/animes-page/animes-page.component.html
> +		<button class="form__submit" type="submit" mat-button color="accent">Find</button>
```suggestion
		<button type="submit" mat-button color="accent">Find</button>
```

2023-07-28 02:57 UTC, pavel-romanov8 commented on apps/angular/src/core/interceptors/error.interceptor.ts
> +			retry(3),
I would avoid having such interceptor for the whole application level. The reason is simple - there are different types of requests. Imagine if we are having highly loaded app place, that involves very active interaction with BE. If such endpoint end up with some problems from BE side we will start sending a lot of retries. In case the app have a lot of users we can simply ddos our server with such code.

The problem that I mentioned above might be resolved with a more complex RX flow that regulate it.

The second problem is poor UX. Imagine if user have a slow internet connection. If we retry every request 3 times the experience will be drastically reduced.

Overall, we should only apply the logic whenever we really need it

2023-07-28 02:57 UTC, pavel-romanov8 commented on libs/core/mappers/anime-type.mapper.ts
> +export namespace AnimeType {
```suggestion
export namespace AnimeTypeMapper {
```

2023-07-28 02:57 UTC, pavel-romanov8 commented on libs/core/models/anime.ts
> +	direction: SortDirection;
Should it be mutable?

2023-07-28 02:57 UTC, pavel-romanov8 commented on libs/core/mappers/ordering.mapper.ts
> +type OrderingHelper = { [key in string]: string };
```suggestion
type OrderingHelper = Record<string, string>;
```

2023-07-28 02:57 UTC, pavel-romanov8 commented on libs/core/mappers/ordering.mapper.ts
> +	 * Converts ordering model to dto.
```suggestion
	 * Converts ordering model to DTO.
```

2023-07-28 02:57 UTC, pavel-romanov8 commented on libs/core/mappers/ordering.mapper.ts
> +	export function toDto(ordering: Ordering | undefined, orderingHelper: OrderingHelper): string | undefined {
Purpose of `orderingHelper` is not quite clear here. Maybe because of the naming. Would be great to improve naming/documentation

2023-07-28 11:45 UTC, pavel-romanov8 requested changes

2023-07-28 11:45 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime/animes-page/animes-page.component.ts
> +	// protected readonly queryParams = new BehaviorSubject<RoutingQueryParams>({ ...defaultRoutingQueryParams });
Please, remove this dead code

2023-07-28 11:45 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime/animes-page/animes-page.component.ts
> +	protected readonly pageSize$ = new BehaviorSubject(defaultRoutingQueryParams.size);
While this approach looks good, we have 1 big problem - data duplication. We have the same data in such subjects as we have in query filter parameters. I would try to make a single source of truth so we don't have to duplicate ourselves.

Hint: we can use query params as a main source of truth.

2023-07-28 11:45 UTC, pavel-romanov8 commented on apps/angular/src/core/interceptors/error.interceptor.ts
> +				this.router.navigate(['/error']);
Do we really need such interceptor at all? I mean, navigating user to the error page every time request fails is really bad UX. What if we have validation error from a form? Instead of showing validation error we are going to navigate user to the page which is not really great

2023-08-01 08:45 UTC, dmitrymaslov13 commented on libs/core/mappers/ordering.mapper.ts
> +		if (!ordering) {
Please dont use implicit typecasting:
https://wiki.saritasa.rocks/frontend/languages/ts-js/best-practices#dont-use-implicit-type-casting

```suggestion
		if (ordering == null) {
```

2023-08-01 08:45 UTC, dmitrymaslov13 commented on libs/core/mappers/ordering.mapper.ts
> +		orderingDirectionMapper: OrderingMapper,
Ordering direction looks like it's the same everywhere. Might be worth revisiting

2023-08-01 19:26 UTC, EgorRyazanov commented on apps/angular/src/app/features/anime/animes-page/animes-page.component.ts
> +				this.isLoading$.next(false);
Yes, I thought the same, but it won't work that way and the loader will continue to work. As far as I understand, finalize only works if the thread is terminated (for example, in case of an error).

2023-08-02 03:29 UTC, kristinaSvobodinaSaritasa commented on apps/angular/src/app/features/anime/animes-page/animes-page.component.ts
> +				this.isLoading$.next(false);
So in this case you don't need to use `finalize` , let's handle errors by `catchError` operator.

2023-08-02 03:49 UTC, kristinaSvobodinaSaritasa commented on apps/angular/src/app/features/anime/animes-page/animes-page.component.ts
> +	protected createAnimesStream(): Observable<AnimePagination> {
Let's remove logic with params to separate private functions, It makes code easy to read

2023-08-02 03:49 UTC, kristinaSvobodinaSaritasa commented on apps/angular/src/core/utils/routing-params.mapper.ts
> +	function isType(value: string): boolean {
```suggestion
	function isAnimeType(value: string): boolean {
```

2023-08-02 03:49 UTC, kristinaSvobodinaSaritasa commented on apps/angular/src/core/utils/routing-params.mapper.ts
> +	function isField(value: string): boolean {
```suggestion
	function isAnimeField(value: string): boolean {
```

2023-08-02 03:49 UTC, kristinaSvobodinaSaritasa commented on apps/angular/src/core/utils/routing-params.mapper.ts
> +		}
```suggestion
		const isChanged =
			pageState.isChanged ||
			sizeState.isChanged ||
			fieldState.isChanged ||
			typeState.isChanged ||
			searchState.isChanged ||
			directionState.isChanged
		
```

2023-08-02 08:15 UTC, gevorg-gevorgyan-saritasa commented on apps/angular/src/core/services/anime.service.ts
> +/** Anime Service. */
I guess it was correct before  🌚
```suggestion
/** Anime service. */
```

2023-08-02 08:15 UTC, gevorg-gevorgyan-saritasa commented on libs/core/models/anime-ordering.ts
> +	TITLE_ENGLISH = 'titleEnglish',
Check linter issues about enums, please.

2023-08-03 09:46 UTC, pavel-romanov8 commented on apps/angular/src/core/interceptors/error.interceptor.ts
> +					return throwError(() => new Error(`Status: ${error.status}; Message: ${error.message}`));
Essentially we are doing the same thing as `ErrorHandler`, right? It is the global error handler in angular, something like global error boundary in React, but without any particular fallbacks

2023-08-03 09:52 UTC, pavel-romanov8 commented on apps/angular/src/core/utils/routing-params.mapper.ts
> +			if (isNumeric(page)) {
Most of the times regular expressions are excessive and we can achieve the same result without them. In you case it might looks something like:
```ts
const newPageNumber = Number(page);
const isValidPageNumber = !Number.isNan(newPageNumber);

return {
  pageNumber: isValidPageNumber ? newPageNumber : defaultQueryparams.pageNumber,
  isChanged: isValidPageNumber,
}
```
Notice that we don't have to work with regexp as well as having the nested `if` blocks

2023-08-03 09:52 UTC, pavel-romanov8 commented on apps/angular/src/shared/directives/anime-type.pipe.ts
> +		return AnimeTypes.toReadable(value as AnimeTypes);
Looks like casting is redundant

2023-08-03 09:58 UTC, pavel-romanov8 commented on apps/angular/src/core/utils/routing-params.mapper.ts
> +			sizeState.isChanged ||
The code is valid, however we can achieve the same result using `distinctUnilChanged` RxJS operator

2023-08-03 10:00 UTC, pavel-romanov8 commented on apps/angular/src/core/utils/routing-params.mapper.ts
> +					modal.push(element as AnimeTypes);
Would be great to work on simplification of this code. It is really hard to read through

2023-08-03 12:58 UTC, EgorRyazanov commented on apps/angular/src/core/utils/routing-params.mapper.ts
> +export interface UnknownAnimeRouringQueryParams {
This interface shows what parameters I am passing, but their types are unknown (I am 110 percent sure that they will come). The user could type anything into search bar, so they are unknown. To avoid problems, I created a function for type checking and, if necessary, bringing values to the defaults. Of course, I could make the whole object type unknown, but this is inconvenient, in my opinion

2023-08-03 13:02 UTC, EgorRyazanov commented on apps/angular/src/core/utils/routing-params.mapper.ts
> +			sizeState.isChanged ||
This status is not about the fact that the user changed the values, but about the fact that he entered invalid ones. In case of invalid value, I reset them to the defaults and set the status "isChanged" to true, so that we can forward the user to a valid link

2023-08-04 00:41 UTC, dbitkovski commented on apps/angular/src/core/utils/routing-params.mapper.ts
> +export interface UnknownAnimeRouringQueryParams {
> The user could type anything into search bar, so they are unknown.
Are you sure? Is a user able to type `boolean` type or `Array`? I believe that the only thing that the user might type into an input is a string

2023-08-04 02:38 UTC, pavel-romanov8 commented on apps/angular/src/core/utils/routing-params.mapper.ts
> +			sizeState.isChanged ||
Then, maybe it would be better to provide appropriate name? Because `isChanged` is not telling us about validity much

2023-08-04 06:38 UTC, dmitrymaslov13 commented on apps/angular/src/app/features/anime/animes-page/animes-page.component.ts
> +	protected trackByAnime(_index: number, anime: Anime): number {
```suggestion
	protected trackByAnime(_index: number, anime: Anime): Anime['id'] {
```

2023-08-04 06:38 UTC, dmitrymaslov13 commented on apps/angular/src/app/features/anime/animes-page/animes-page.component.ts
> +	private proccessQueries(query: Params): StatusedRoutingParams {
The name of the method is confusing. JSDOC and code suggested what is being done here. Let's rename it.
If i understand correct you map query params to model with params

2023-08-04 06:38 UTC, dmitrymaslov13 commented on apps/angular/src/app/features/anime/animes-page/animes-page.component.ts
> +	private fillOutForm(params: AnimeRoutingQueryParams): void {
maybe something like `setFormValues` ?

2023-08-04 06:38 UTC, dmitrymaslov13 commented on apps/angular/src/core/utils/anime-routing-params.mapper.ts
> +	}
```suggestion
	function isType<T extends string>(value: T, validatingEnum: Enum): boolean {
		return Object.values(validatingEnum).includes(value);
	}
```

2023-08-04 06:38 UTC, dmitrymaslov13 commented on apps/angular/src/core/utils/anime-routing-params.mapper.ts
> +	export function pageToModel(page: unknown): IncomeStatusedQueryParams<Pick<AnimeRoutingQueryParams, 'pageNumber'>> {
according to your code, you use this method only where you pass a string or string array.

you can get rid of line checks in all fields in similar functions

2023-08-04 06:38 UTC, dmitrymaslov13 commented on libs/core/mappers/ordering.mapper.ts
> +		orderingDirectionMapper: OrderingMapper,
Hmm, I see nothing has changed, but you marked the comment as solved. Tell me what you decided, or explain the reason why the comment is not appropriate (this may well be if I did not understand the idea or do not know the details)

2023-08-04 08:52 UTC, dmitrymaslov13 commented on libs/core/dtos/anime-ordering.dto.ts
> +export enum OrderingDirectionDto {
Let's move to separate file

2023-08-04 08:52 UTC, dmitrymaslov13 commented on apps/angular/src/core/utils/anime-routing-params.mapper.ts
> +	function isType<T extends string>(value: T, validatingEnum: Enum): boolean {
If I not wrong you use `Enum` in only this case
If it true, let's remove `Enum` type and use In here Record

else mark comment as solved

2023-08-04 09:02 UTC, dmitrymaslov13 approved these changes

2023-08-04 09:19 UTC, merged