Feature/jc 549 authorization
saritasa-nest/camp-js-2023-egor-ryazanov pull request #6
Opened 2023-08-04 10:16 UTC by EgorRyazanov

2023-08-06 13:42 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/app/features/auth/login/login.component.html
> +	<a routerLink="/auth/register" class="auth-link" href="">Еще нет аккаунта?</a>
Please be consistent with language

2023-08-06 13:42 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/core/services/url.service.ts
> +	}
I think docs here aren't explaining it properly. I suggest - 'Checks url for ...'

2023-08-06 13:42 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/core/services/storage.service.ts
> +	 * Removed data from storage.
```suggestion
	 * Remove data from storage.
```

2023-08-06 13:42 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/core/services/storage.service.ts
> +				return of(JSON.parse(value));
Please handle errors, `JSON.parse('')` will throw an error if value isn't valid JSON.

2023-08-06 13:42 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/core/guards/authorized.guard.ts
> +	return userService.isAuthorized$.pipe(map(isAuthorized => (isAuthorized ? isAuthorized : router.parseUrl('/'))));
1. Please prefer placing operators each on a new line, even if there is one operator. It helps with readability
2. `map` operator shouldn't have side effects inside it.

2023-08-06 13:42 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/core/services/user.service.ts
> +			first(isAuthorized => Boolean(isAuthorized)),
You can write it simply like this
```suggestion
			first(Boolean),
```

2023-08-06 13:42 UTC, artem-sotnichenko-saritasa commented on libs/core/dtos/auth-dto/register.dto.ts
> +	readonly last__name: string;
Is it a typo or is it intentional?

2023-08-06 13:42 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/theme/variables.css
> +  --space-sm: 8px;
I suggest using `calc` here too, for consistency.

2023-08-06 13:42 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/core/interceptors/auth.interceptor.ts
> +			);
Do you really need to create variable here?
```suggestion
			return this.userSecretStorage.currentSecret$.pipe(
				first(),
				map(userSecret =>
					userSecret ? 
						req.clone({ headers: this.appendAuthorizationHeader(req.headers, userSecret) }) : 
						req),
				switchMap(newReq => next.handle(newReq)),
			);
```

2023-08-07 10:19 UTC, dmitrymaslov13 requested changes

2023-08-07 10:19 UTC, dmitrymaslov13 commented on libs/core/models/auth/register.ts
> +	/** Lastname. */
Why?

2023-08-07 10:19 UTC, dmitrymaslov13 commented on libs/core/mappers/error.mapper.ts
> +	const FORM_FIELD_FROM_DTO: Record<string, string> = {
I understand why you decided that, you really have a specific error format on the server.
But now we have at least 3 serious problems:

1) All variable names from backend and domain are global and not typed. If you have a new form, or 10 new forms with different values, you will have to update this object, but we still won't have typing.
2) Received errors in AppError are not typed.
3) We tightly tie up server names with domain names

Let's fix this

2023-08-08 03:44 UTC, pavel-romanov8 requested changes

2023-08-08 03:44 UTC, pavel-romanov8 commented on apps/angular/src/app/app-routing.module.ts
> +		title: 'Animes',
Can we move this base route with component to `AnimeModule` as well? It makes the high level routing structure a bit cleaner

2023-08-08 03:44 UTC, pavel-romanov8 commented on apps/angular/src/app/features/auth/login/login.component.html
> +		<mat-error *ngIf="commonErrors$ | async as error">
Is there a point of having `ngIf` directive here and on the `div` above? Would be great to have only 1 place where we extract the errors

2023-08-08 03:44 UTC, pavel-romanov8 commented on apps/angular/src/app/features/auth/login/login.component.html
> +			<mat-error *ngIf="loginForm.controls.email.hasError('required') && loginForm.controls['email'].touched">
1. Please, use consistent approach for retrieving particular control. You are using mix of indexed and dot notation.
2. Would be great to move such things into getter functions with descriptive names. That way we can hide this complexity in component. Something like `isEmailInvalid` should work

2023-08-08 03:44 UTC, pavel-romanov8 commented on apps/angular/src/app/features/auth/login/login.component.html
> +			<mat-error *ngFor="let error of loginForm.controls.email.getError('invalid')">
Don't you think is a bit too much to show so many errors? You already have errors for required field and valid email above

2023-08-08 03:44 UTC, pavel-romanov8 commented on apps/angular/src/app/features/auth/login/login.component.html
> +	<a routerLink="/auth/register" class="auth-link" href="">Do not have an account yet?</a>
There is no need to provide `href`
```suggestion
	<a routerLink="/auth/register" class="auth-link">Do not have an account yet?</a>
```

2023-08-08 03:44 UTC, pavel-romanov8 commented on apps/angular/src/app/features/auth/login/login.component.ts
> +	protected login(): void {
We can match the name with docs to make it more clear. Also, we usually use `on` prefix for template handlers
```suggestion
	protected onSubmit(): void {
```

2023-08-08 03:44 UTC, pavel-romanov8 commented on apps/angular/src/app/features/auth/login/login.component.ts
> +		if (this.loginForm.invalid !== true) {
This condition too complicated. I would recommend tweaking it a bit to make code more readable and move main logic out of the `if` block:
```ts
this.loginForm.markAllAsTouched();

if (this.loginForm.invalid) {
  return;
}

// rest of the logic goes here
```

2023-08-08 03:44 UTC, pavel-romanov8 commented on apps/angular/src/app/features/auth/login/login.component.ts
> +				.login(this.loginForm.value as Login)
Why do you need casting? If it is because of the `Partial` type we can use `getRawValue()` instead

2023-08-08 03:44 UTC, pavel-romanov8 commented on apps/angular/src/app/features/auth/login/login.component.ts
> +								this.commonErrors$.next(errors.validationData.nonFieldErrors);
Does it make sense to have extra errors when you already have `catchFormErrors`?

2023-08-08 03:44 UTC, pavel-romanov8 commented on apps/angular/src/app/features/auth/login/login.component.ts
> +					first(),
There is no need to use `first` in this case since you already have `takeUntilDestroy` at the end

2023-08-08 03:44 UTC, pavel-romanov8 commented on apps/angular/src/app/features/auth/login/login.component.ts
> +						this.isLoading$.next(false);
Be very careful with such logic. We are heavily relying on the fact that stream should be completed in order to hide loading state, but if you were to have any inner subscriptions it won't simply work. What I recommend doing instead is to rely on all 3 callbacks (next/error/complete) and turn loading state back whenever one of them is called. You can create some utility function for it.

P.S. `tap` has the same configuration as `subscribe`, so you can try using it for loading state handling

2023-08-08 03:44 UTC, pavel-romanov8 commented on apps/angular/src/app/features/auth/register/register.component.ts
> +	protected readonly isLoading$ = new BehaviorSubject<boolean>(false);
We can rely on typescript
```suggestion
	protected readonly isLoading$ = new BehaviorSubject(false);
```

2023-08-08 03:44 UTC, pavel-romanov8 commented on apps/angular/src/app/features/auth/register/register.component.ts
> +	protected readonly registerForm: FormGroup<RegisterForm>;
_register_ sounds like a verb which is more common for functions
```suggestion
	protected readonly registrationForm: FormGroup<RegisterForm>;
```

2023-08-08 03:44 UTC, pavel-romanov8 commented on apps/angular/src/app/features/base-page/base-page.component.ts
> +	private readonly destroyRef = inject(DestroyRef);
You can place private class fields below protected

2023-08-08 03:44 UTC, pavel-romanov8 commented on apps/angular/src/core/guards/unauthorized.guard.ts
> +export const UnauthorizedGuard: CanActivateFn = () => {
Please, follow the same case as `authorizedGuard`. There is no need to use PascalCase

2023-08-08 03:44 UTC, pavel-romanov8 commented on libs/core/dtos/error.dto.ts
> +	readonly detail: string;
Please, keep the docs in place for this type as well

2023-08-08 03:44 UTC, pavel-romanov8 commented on libs/core/mappers/auth/login-data.mapper.ts
> +		return data;
While the object shape is the same we prefer explicit mapping over passing it as is. That way we can see and fix errors more efficiently

2023-08-08 03:44 UTC, pavel-romanov8 commented on libs/core/mappers/auth/login-data.mapper.ts
> +	email = 'email',
Can we use PascalCase?

2023-08-08 03:44 UTC, pavel-romanov8 commented on libs/core/mappers/auth/user-secret.mapper.ts
> +		return dto;
Same thing with explicit mapping

2023-08-08 03:44 UTC, pavel-romanov8 commented on libs/core/mappers/mappers.ts
> +export interface IValidationErrorMapper<TDomain> {
There is no point of having `I` for all these interfaces. We should change it in our boilerplate as well

2023-08-08 03:44 UTC, pavel-romanov8 commented on libs/core/tsconfig.app.json
> +	"include": ["**/*.ts", "../../apps/angular/src/core/utils/app-error.mapper.ts", "mappers/auth/login-data.mapper.ts"]
Why we include angular specific types in core library?

2023-08-08 08:49 UTC, EgorRyazanov commented on apps/angular/src/app/features/auth/login/login.component.ts
> +								this.commonErrors$.next(errors.validationData.nonFieldErrors);
Here I catch global form errors that do not apply to others controls

2023-08-08 08:53 UTC, EgorRyazanov commented on apps/angular/src/app/features/auth/login/login.component.html
> +			<mat-error *ngFor="let error of loginForm.controls.email.getError('invalid')">
I was wrong here. I now output one server error of this field. But still there are 3 error outputs in general. Should I redo it still?

2023-08-09 14:51 UTC, dmitrymaslov13 commented on apps/angular/src/app/features/auth/auth.css
> +  z-index: 100;
Let's add comment why you use `z-index`

2023-08-09 14:51 UTC, dmitrymaslov13 commented on libs/core/models/auth/user-secret.ts
> +	public readonly access: string;
it's a domain model, you can rename this fields (`accessToken` `refreshToken`) because `refresh` sounds like verb

2023-08-09 14:51 UTC, dmitrymaslov13 commented on libs/core/models/auth/register.ts
> +export class Register {
`Register` sounds like a verb

2023-08-09 14:51 UTC, dmitrymaslov13 commented on libs/core/mappers/auth/register-data.mapper.ts
> +	FirstName = 'first__name',
I'm glad you took a look and understood how the validation errors from our boilerplate work.

But now we have a potential place that could break the application or cause unexpected behavior.

Look, if the field names are partially changed on the backend, or a new one is added, and we will not edit anything in the enum, the typescript will not tell us that something is wrong.

2023-08-10 04:26 UTC, pavel-romanov8 approved these changes

2023-08-10 04:26 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime/animes-page/animes-page.component.ts
> +		const urlWithoutParams = this.router.url.split('?')[0];
Prefer using `at` since it is more type-safe (return type is `T | undefined`)

2023-08-10 04:26 UTC, pavel-romanov8 commented on apps/angular/src/app/features/auth/login/login.component.ts
> +	protected hasServerError(controlName: string): string | boolean {
Can we make the type of control name as `keyof LoginForm` to avoid casting?

2023-08-10 04:26 UTC, pavel-romanov8 commented on apps/angular/src/app/features/auth/login/login.component.ts
> +			return this.loginForm.controls[controlName as keyof LoginForm].getError('invalid');
The function signature looks a bit loaded. From the name only I can tell the you would only check whether control has an error or not (like other methods), but in fact I'm getting the error name back from it. I would rather rename it to `get*` and return `null` if there is no such error

2023-08-10 04:26 UTC, pavel-romanov8 commented on apps/angular/src/app/features/auth/login/login.component.ts
> +	protected hasServerError(controlName: string): string | boolean {
Please, try to avoid any mentions of the _server_, _dto_ and other parts of the app that are not directly tight to this layer

2023-08-10 04:26 UTC, pavel-romanov8 commented on libs/core/mappers/auth/register-data.mapper.ts
> +	FirstName = 'first__name',
Can we leave it as it is for now? There are a lot of things that can go wrong with BE and handling all of them would be too much for this task. Even our boilerplates have a flaws in this regard

2023-08-10 05:36 UTC, dmitrymaslov13 commented on libs/core/mappers/auth/register-data.mapper.ts
> +	FirstName = 'first__name',
Okay
But at least it is useful to understand that there is such a problem.

2023-08-10 06:51 UTC, dmitrymaslov13 approved these changes

2023-08-10 07:44 UTC, merged