Feature/jc 555 anime details
saritasa-nest/camp-js-2023-egor-ryazanov pull request #7
Opened 2023-08-10 07:46 UTC by EgorRyazanov

2023-08-11 07:51 UTC, AndreySkripachev commented on apps/angular/src/app/features/anime/anime-details-page/anime-details-page.component.html
> +			<img class="details__image" [alt]="anime.titleEnglish" [src]="anime.image" (click)="openDialog(anime.image)" />
If there are more than 3 attributes, they should be placed in different lines
```suggestion
			<img 
						class="details__image" 
						[alt]="anime.titleEnglish" 
						[src]="anime.image" 
		        			(click)="openDialog(anime.image)" 
			/>
```

2023-08-11 07:51 UTC, AndreySkripachev commented on apps/angular/src/app/features/anime/anime-details-page/components/dialog/image-dialog.component.html
> +	<img alt="anime-full-size-image" class="image" [src]="data.imageUrl" />
I think the text in the alt attribute will not give the user any information in case the picture fails to load

2023-08-11 07:51 UTC, AndreySkripachev commented on apps/angular/src/app/features/base-page/base-page.component.html
> +	<a class="header__title-link" routerLink="/">
This looks odd to me, since you're putting a block element in a line element. You could put the link inside the header

You can see [here](https://caninclude.glitch.me/caninclude?child=h2&parent=a) why you shouldn't put `h2` tags in `a`

2023-08-11 07:51 UTC, AndreySkripachev commented on apps/angular/src/core/interceptors/auth.interceptor.ts
> +		// console.log9)
That doesn't seem like it should be here.

2023-08-11 07:51 UTC, AndreySkripachev commented on apps/angular/src/shared/directives/readable-genres.pipe.ts
Why did you put the pips in the directives folder?

2023-08-11 07:51 UTC, AndreySkripachev commented on apps/angular/src/shared/directives/readable-source.pipe.ts
> +		return Source.toReadable(source);
These pipes are very similar to each other and it looks like code duplication. You can make one pipe that will, for example, accept a value and a mapper with the `toReadable(value)` method.

2023-08-11 08:36 UTC, maxineo reviewed
There are several undocumented exported members across all files, so please revise them.

2023-08-11 08:36 UTC, maxineo commented on apps/angular/src/app/features/anime/anime-details-page/anime-details-page.component.css
> +.details__image {
I see no `details` block. Perhaps it should be `anime__details-image`?

2023-08-11 08:36 UTC, maxineo commented on apps/angular/src/app/features/anime/anime-details-page/anime-details-page.component.css
> +  margin-bottom: var(--space-md);
Try to position elements from parent. That way it will be a lot easier to reuse them. [wiki](https://wiki.saritasa.rocks/frontend/languages/css#componentselements-should-not-position-themselves)

2023-08-11 08:36 UTC, maxineo commented on apps/angular/src/app/features/anime/anime-details-page/components/dialog/image-dialog.component.ts
> +	imageUrl: string;
Missing `readonly`.

2023-08-11 08:36 UTC, maxineo commented on apps/angular/src/shared/directives/readable-source.pipe.ts
> +		return Source.toReadable(source);
I think we can just use generic type.

2023-08-11 08:36 UTC, maxineo commented on libs/core/dtos/anime-dto/anime-details.dto.ts
> +export enum SeasonsDTO {
Why dto is written with all uppercase letters here and in the next enum while it has only first uppercasse letter in other cases?

2023-08-11 08:36 UTC, maxineo commented on libs/core/dtos/anime-dto/anime-details.dto.ts
> +export enum SourceDTO {
Missing comment.

2023-08-11 08:36 UTC, maxineo commented on libs/core/dtos/anime-dto/anime-details.dto.ts
> +export interface AnimeDetailDto {
Missing comment.

2023-08-11 08:36 UTC, maxineo commented on libs/core/dtos/studios-dto/studio.dto.ts
> +export interface StudioDTO {
Missing documentation.

2023-08-11 08:36 UTC, maxineo commented on libs/core/models/anime/anime-detail.ts
> +	end: Date | null;
Is there a reason why these are not `readonly`?

2023-08-14 15:38 UTC, dmitrymaslov13 requested changes
And your demo not working)
I not can open anime details

2023-08-14 15:38 UTC, dmitrymaslov13 commented on apps/angular/src/shared/pipes/yes-no.pipe.ts
> +export class YesNo implements PipeTransform {
Angular entities usually have an ending that describes what they mean.
In this case expected `YesNoPipe` class name

2023-08-14 15:38 UTC, dmitrymaslov13 commented on apps/angular/src/shared/pipes/readable.pipe.ts
> +export class Readable implements PipeTransform {
Same about naming, but please save your time.
I understand what your decision is dictated by, but this approach has several problems

1) Lack of typing for incoming parameters.
2) Non-obvious behavior when passing a type that is not taken into account, it is not very obvious that the same thing will be returned as passed before
3) The need to enter into this file all new types that will appear in the future (we don't want to be non-consistent :D)
4) Very unreadable transform method with infinite `if` `else`

Have you heard of the **god object** antipattern?
In short, it's about an object that stores a lot of things, or does a lot of different things

It violates **S** from **SOLID** (S - Single Responsibility)
which in short says that each method / class should be responsible for its own responsibility

In your case class have responsible for map to readable Source/Rating/AnimeType/... (more than one, right? :D )

Let's transform this into small and beautiful pipes, each of which is responsible for its own type.

And i advise you to read about **SOLID** to keep in mind in the process what it means

2023-08-14 15:41 UTC, dmitrymaslov13 commented on apps/angular/src/shared/pipes/readable.pipe.ts
> +export class Readable implements PipeTransform {
I saw other guys comments about this.
@maxineo, @AndreySkripachev what do you think about it? Maybe did you mean something else?

2023-08-14 15:49 UTC, dmitrymaslov13 commented on apps/angular/src/app/features/anime/anime-details-page/components/dialog/image-dialog.component.ts
> +	public constructor(@Inject(MAT_DIALOG_DATA) public data: ImageDialogData) {}
Just for you know: 

i see you use `inject` sometimes.
You can use `inject` for inject `MAT_DIALOG_TOKEN` token.

```suggestion
	protected readonly data = inject<ImageDialogData>(MAT_DIALOG_DATA);
```

2023-08-14 18:54 UTC, EgorRyazanov commented on apps/angular/src/app/features/anime/animes-page/animes-page.component.css
> +tr.table__row:hover {
It's does not working like this, idk why, i tried few variants, but stackoverflow gave me such answer

2023-08-14 19:00 UTC, EgorRyazanov commented on apps/angular/src/core/services/anime.service.ts
> +@Injectable()
I figured that this is the anime service that will perform logic exclusively in anime module. Why not?

2023-08-14 19:08 UTC, EgorRyazanov commented on apps/angular/src/app/features/anime/anime-details-page/components/dialog/image-dialog.component.ts
> +	imports: [MatDialogModule, MatButtonModule],
I forgot to fix it when I was doing it

2023-08-15 05:43 UTC, viktor-sakhno-saritasa requested changes

2023-08-15 05:43 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/features/anime/anime-details-page/anime-details-page.component.html
> +</div>
Can we avoid redundant `div` and set structural directive with class directly to `camp-spinner`?
```suggestion
<camp-spinner *ngIf="isLoading$ | async" class="anime__spinner" />
```

2023-08-15 05:43 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/features/anime/anime-details-page/anime-details-page.component.html
> +	<ng-container *ngIf="anime$ | async as anime">
```suggestion
<div class="anime" *ngIf="anime$ | async as anime">
```

2023-08-15 05:43 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/features/anime/anime-details-page/anime-details-page.component.html
> +			<div>
Please, revise your HTML, maybe we could make it better and write more semantic HTML? For example, it can be `article` instead `div`. Don't forget about UX and semantic when your app has content.

2023-08-15 05:43 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/features/anime/anime-details-page/anime-details-page.component.html
> +				<p><strong>Season:</strong> {{ anime.season | readable }}</p>
The `<strong>` HTML element indicates that its contents have strong importance, seriousness, or urgency. So, if you added it only to **bold** text, let's use CSS.

2023-08-15 05:43 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/features/anime/anime-details-page/anime-details-page.component.html
> +				(click)="openDialog(anime.imageUrl, anime.titleEnglish)"
If you do some element interactive, don't forget to check - does this element have access from keyboard?

2023-08-15 05:43 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/features/anime/anime-details-page/anime-details-page.component.html
> +				<p><strong>Modified:</strong> {{ anime.modified | date | empty }}</p>
Revise formatting, please.
```suggestion
				<p><strong>Modified:</strong>{{ anime.modified | date | empty }}</p>
```

2023-08-15 05:43 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/features/anime/anime-details-page/anime-details-page.component.html
> +			></iframe>
What if we make a standalone component which purpose to show such content? What do you think?

2023-08-15 05:43 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/features/anime/anime-details-page/anime-details-page.component.ts
> +	protected readonly id$: Observable<string>;
Why does this property have `protected` modifier? I don't see where you are using it on template.

2023-08-15 05:43 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/features/anime/anime-details-page/anime-details-page.component.ts
> +			}),
```suggestion
			tap(() => this.isLoading$.next(true)),
```

2023-08-15 05:43 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/features/anime/anime-details-page/anime-details-page.component.ts
> +			stopLoadingStatus(this.isLoading$),
If you have `stopLoadingStatus`, maybe it would be better to create `startLoadingStatus` or something else?

2023-08-15 05:43 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/features/anime/anime-details-page/anime-details-page.component.ts
> +			catchError((error: unknown) => {
Maybe, we notify user about what happened? For example, show dialog or something like that.

2023-08-15 05:43 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/features/anime/animes-page/animes-page.component.css
> +tr.table__row:hover {
It doesn't work due to selector specificity)

2023-08-15 05:43 UTC, viktor-sakhno-saritasa commented on apps/angular/src/shared/pipes/readable.pipe.ts
> +	public transform(value: readonly unknown[] | string): readonly unknown[] | string {
I think it would be better to create several separates pipes to keep single responsibility approach. At the moment, this class is very fragile, and it will change every time when you want to add a new entity.

2023-08-15 05:43 UTC, viktor-sakhno-saritasa commented on apps/angular/src/shared/pipes/readable.pipe.ts
> +				return StudioMapper.toReadable(value);
Also, `toReadable` isn't a task for mappers. It is a UI related feature. So, I think we can add `toReadable` to `Studio` namespace or something like that.

2023-08-15 05:43 UTC, viktor-sakhno-saritasa commented on libs/core/dtos/anime-dto/anime-details.dto.ts
> +
Remove empty line, pls.

2023-08-15 05:43 UTC, viktor-sakhno-saritasa commented on libs/core/mappers/aired.mapper.ts
> +export namespace Airing {
Usually, we sync our file name and main class what we export. So, if you have mapper for `aired` entity, let's name our namespace like `AiredMapper`.

2023-08-15 13:09 UTC, pavelzadorin-saritasa requested changes

2023-08-15 13:09 UTC, pavelzadorin-saritasa commented on apps/angular/src/shared/pipes/readable.pipe.ts
> +	public transform(value: readonly unknown[] | string): readonly unknown[] | string {
I completely agree, remember I said about code smells, look: https://refactoringguru.cn/smells/switch-statements
Think, or let's discuss how you can replace it.

2023-08-16 13:08 UTC, EgorRyazanov commented on apps/angular/src/app/features/anime/anime-details-page/anime-details-page.component.html
> +				<p><strong>Modified:</strong> {{ anime.modified | date | empty }}</p>
I need this space.
With space: 
![image](https://github.com/saritasa-nest/camp-js-2023-egor-ryazanov/assets/89483642/24eddbce-8ea8-463d-bcd3-282a03c5f932)
Without space:
![image](https://github.com/saritasa-nest/camp-js-2023-egor-ryazanov/assets/89483642/60711771-ecf7-4e78-9f70-dfe091e05967)

2023-08-17 03:23 UTC, khoanguyen-saritasa approved these changes

2023-08-17 03:23 UTC, khoanguyen-saritasa commented on apps/angular/src/app/features/anime/animes-page/animes-page.component.ts
>  	protected readonly isLoading$ = new BehaviorSubject(false);
Wrong docs.

2023-08-17 04:11 UTC, viktor-sakhno-saritasa approved these changes

2023-08-17 04:11 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/features/base-page/base-page.component.ts
> +	/** Router. */
It's not required to comment private properties, especially, such properties like `router`, `destroyRef`, etc. It's clear.

2023-08-17 04:36 UTC, dbitkovski approved these changes

2023-08-17 04:36 UTC, dbitkovski commented on apps/angular/src/app/features/anime/anime-details-page/anime-details-page.component.ts
> +	private readonly id$: Observable<string>;
Why do you need separate stream for id? I think you can get it within `createAnimeStream` method

2023-08-17 04:36 UTC, dbitkovski commented on apps/angular/src/shared/pipes/yes-no.pipe.ts
> +		return value ? 'Yes' : 'No';
What if value is `null` or `undefined`? I believe ts type-checking doesn't help here

2023-08-17 05:53 UTC, EgorRyazanov commented on apps/angular/src/app/features/anime/animes-page/animes-page.component.html
> +				<td mat-cell *matCellDef="let anime">{{ animeStatus.toReadable(anime.status) }}</td>
I was talking about this with @pavelzadorin-saritasa and @dmitrymaslov13. They said its extra wrapper. Maybe I misunderstood them

2023-08-18 06:37 UTC, dmitrymaslov13 requested changes

2023-08-18 06:37 UTC, dmitrymaslov13 commented on libs/core/models/anime/anime-type.ts
> +		return null;
```suggestion
	export function toReadable(value: AnimeType): string {
		return TO_TITLE_MAP[value];
```

2023-08-18 06:37 UTC, dmitrymaslov13 commented on libs/core/models/season.ts
> +	}
```suggestion
	export function toReadable(season: Season): string {
		return TO_TITLE_MAP[season];
	}
```

2023-08-18 06:37 UTC, dmitrymaslov13 commented on libs/core/models/anime/anime-status.ts
> +		return null;
```suggestion
	export function toReadable(value: AnimeStatus): string {
		return TO_TITLE_MAP[value];
```

2023-08-18 06:37 UTC, dmitrymaslov13 commented on libs/core/models/anime/anime-source.ts
> +	}
```suggestion
	export function toReadable(source: Source): string {
		return TO_TITLE_MAP[source];
	}
```

2023-08-18 06:37 UTC, dmitrymaslov13 commented on apps/angular/src/shared/components/video-player/video-player.component.ts
> +		}
This component looks like a reusable component, but have problem with pass input `null` after pass `string` url, video will not be lost

2023-08-18 06:37 UTC, dmitrymaslov13 commented on apps/angular/src/core/services/error-dialog.service.ts
> +	private readonly errorDialog = inject(MatDialog);
the name is somewhat misleading.
it is a tool to open any material dialogs

2023-08-18 06:37 UTC, dmitrymaslov13 commented on apps/angular/src/core/services/auth-api.service.ts
> +
```suggestion
```

2023-08-18 06:37 UTC, dmitrymaslov13 commented on apps/angular/src/core/services/anime.service.ts
> +			.pipe(map(dto => AnimeDetailMapper.fromDto(dto)));
Just for you know: 

I see that errors in such requests are not processed in the application.

But I would like you to keep in mind that any errors on the domain layer should refer to the domain layer.

If this request throws an error and you try to catch that error in the application now, you will catch a server error, not an domain error.

You can mark a comment as resolved, or embed mappers for domain errors in requests. The purpose of this comment is just to tell you about it

2023-08-18 06:37 UTC, dmitrymaslov13 commented on apps/angular/src/app/features/anime/anime-details-page/anime-details-page.component.ts
> +				return throwError(() => error);
Oops, I missed this point in the comments about the errors.
Abstraction emissions have occurred here
We should not work with server errors and catch them at the domain and UI layers!

2023-08-18 07:19 UTC, dmitrymaslov13 approved these changes

2023-08-21 06:07 UTC, pavelzadorin-saritasa approved these changes

2023-08-21 06:51 UTC, merged