Feature/jc 565 item management
saritasa-nest/camp-js-2023-egor-ryazanov pull request #9
Opened 2023-08-21 12:30 UTC by EgorRyazanov

2023-08-22 10:58 UTC, timofei-maximov-saritasa commented on apps/angular/src/app/features/anime/anime-details-page/anime-details-page.component.html
> +		<button mat-icon-button type="button" (click)="navigateToEditPage()">
Your button serves here as a link. So, can we replace it with link element?

2023-08-22 10:58 UTC, timofei-maximov-saritasa commented on apps/angular/src/app/features/anime/anime-details-page/anime-details-page.component.html
> +		<button type="button" (click)="navigateToCreatePage()" mat-raised-button>Create anime</button>
Same here

2023-08-22 10:58 UTC, timofei-maximov-saritasa commented on apps/angular/src/app/features/anime/manage-anime/anime-form/anime-form.component.css
> +  width: 49%;
Is there a reason for such strange values?

2023-08-22 10:58 UTC, timofei-maximov-saritasa commented on apps/angular/src/core/services/confirm.service.ts
> +	public constructor(private readonly confirmDialog: MatDialog) {}
Will it only be for confirm dialog? I think we can rename it to something like `DialogsService` to utilize common dialogs in the future (like some sort of alerts)


Overall, good idea with a service for common dialog cases!

2023-08-22 10:58 UTC, timofei-maximov-saritasa commented on apps/angular/src/app/features/anime/manage-anime/anime-form/anime-form.component.ts
> +	}
Can you explain, why did you need these over a single input field like this:

```ts
@Input()
public readonly title: string
```

2023-08-22 10:58 UTC, timofei-maximov-saritasa commented on apps/angular/src/app/features/anime/manage-anime/anime-form/anime-form.component.ts
> +	protected readonly statusOptions = Object.values(AnimeStatus).slice(0, -1);
Why do you need `slice` here?

2023-08-22 10:58 UTC, timofei-maximov-saritasa commented on apps/angular/src/app/features/anime/manage-anime/anime-form/anime-form.component.ts
> +					return this.genresService.create({ name: params.name, pageNumber: params.pageNumber });
You don't use `pageNumber` in `create` method, let's omit it

2023-08-22 10:58 UTC, timofei-maximov-saritasa commented on apps/angular/src/shared/components/confirm-dialog/confirm-dialog.component.ts
> +	message: string;
Missing `readonly` modifier

2023-08-22 10:58 UTC, timofei-maximov-saritasa commented on apps/angular/src/shared/components/custom-form-select/custom-form-select.component.ts
> +			.subscribe();
Don't forget to unsubscribe

2023-08-22 11:18 UTC, andrey-gazzaev commented on apps/angular/src/app/features/anime/anime-details-page/anime-details-page.component.ts
> +			.subscribe();
Also, don't forget to manage your subscriptions

2023-08-22 11:26 UTC, andrey-gazzaev commented on apps/angular/src/app/features/anime/manage-anime/anime-form/anime-form.component.ts
> +				first(),
```suggestion
		
```

`first` is redundant. The response from the server will only be emit once anyway

2023-08-22 11:27 UTC, andrey-gazzaev commented on apps/angular/src/app/features/anime/manage-anime/anime-form/anime-form.component.ts
> +					}
Why don't you use a ternary operator?

2023-08-22 11:32 UTC, andrey-gazzaev commented on apps/angular/src/app/features/anime/manage-anime/anime-form/anime-form.component.ts
> +			modified: this.formBuilder.control(DEFAULT_ANIME_DETAILS_FORM.modified),
As far as I know, the `created` and `modified` fields are used by the internal `BE` mechanisms. I'm not sure if you can or should try to change them. They will probably be managed by the `BE` itself.

2023-08-22 11:34 UTC, andrey-gazzaev commented on apps/angular/src/app/features/anime/manage-anime/edit-anime-page/edit-anime-page.component.ts
> +export class EditAnimePageComponent {
```suggestion
export class AnimeEditComponent {
```
Class names should be noun, not verb

2023-08-22 11:35 UTC, andrey-gazzaev commented on apps/angular/src/app/features/base-page/base-page.component.html
> +		<a class="header__title-link" routerLink="/">AnimeHub</a>
Let's add a `title` attribute to this link. Since `AnimeHub` is not informative.

2023-08-22 11:48 UTC, andrey-gazzaev commented on libs/core/models/anime/anime-details-form.ts
> +		this.imageFile = animeDetailData.imageFile;
Aren't you tired of writing that? Let's use `Interface`. :)

2023-08-22 17:34 UTC, EgorRyazanov commented on apps/angular/src/app/features/anime/manage-anime/anime-form/anime-form.component.ts
> +					}
I dont use ternary operator, because there some eslint errors
![image](https://github.com/saritasa-nest/camp-js-2023-egor-ryazanov/assets/89483642/a6f5d85b-bdca-4da6-8c16-13408c9c72ce)

2023-08-23 04:26 UTC, golovachev-yaroslav approved these changes

2023-08-24 02:31 UTC, andrey-gazzaev approved these changes

2023-08-24 02:31 UTC, andrey-gazzaev commented on apps/angular/src/app/features/anime/manage-anime/anime-form/anime-form.component.ts
> +					return this.genresService.create({ name: params.name, pageNumber: params.pageNumber });
Why do you need the `pageNumber` parameter to create an entity?

2023-08-25 10:57 UTC, timofei-maximov-saritasa approved these changes

2023-08-25 10:57 UTC, timofei-maximov-saritasa commented on apps/angular/src/app/features/anime/anime-details-page/anime-details-page.component.html
> +		<a title="Anime create page" type="button" (click)="navigateToCreatePage()" mat-raised-button>Create anime</a>
Let's use `routerLink` prop over `click`.

2023-08-25 14:56 UTC, gevorg-gevorgyan-saritasa approved these changes

2023-08-25 14:56 UTC, gevorg-gevorgyan-saritasa commented on apps/angular/src/shared/components/custom-form-select/custom-form-select.component.html
> +	class="auto-complete"
```suggestion
	class="autocomplete"
```

2023-08-25 16:15 UTC, dmitrymaslov13 requested changes

2023-08-25 16:15 UTC, dmitrymaslov13 commented on apps/angular/src/shared/components/custom-form-select/custom-form-select.component.ts
> +	public getItems = new EventEmitter<DefaultParams>();
I think name `paramsChange` will be more descriptive

2023-08-25 16:15 UTC, dmitrymaslov13 commented on apps/angular/src/shared/components/custom-form-select/custom-form-select.component.ts
> +	}
You not use this getter.

2023-08-25 16:15 UTC, dmitrymaslov13 commented on apps/angular/src/shared/components/custom-form-select/custom-form-select.component.ts
> +	private _items: T[] = [];
I not understand idea. You use it only in items setter, but you can get this values from `filteredItems$.value`

2023-08-26 19:34 UTC, dmitrymaslov13 approved these changes
Good job! Let's correct those moments about which I wrote.

2023-08-26 19:34 UTC, dmitrymaslov13 commented on apps/angular/src/app/features/anime/anime-details-page/anime-details-page.component.ts
> +				)),
Why u use `concatMap` in this case?
looks like a `switchMap` here is quite enough

2023-08-26 19:34 UTC, dmitrymaslov13 commented on apps/angular/src/app/features/anime/anime-details-page/anime-details-page.component.ts
> +				)),
By the way! to simplify the logic, you can take values not from streams, but pass them in a template, so the method will look simpler

```ts
protected openDeleteConfirmationDialog(id: Anime['id']): void
```
or
```ts
protected openDeleteConfirmationDialog(anime: Anime): void
```

2023-08-26 19:34 UTC, dmitrymaslov13 commented on apps/angular/src/app/features/anime/anime-details-page/anime-details-page.component.ts
> +		}));
Let's move this pipe creation to separate method.

By the way, I see that you don't use this field anywhere (if you chagne the remove method), so you can put it in a separate method and create it inside the `createAnimeStream`

2023-08-26 19:34 UTC, dmitrymaslov13 commented on apps/angular/src/app/features/anime/anime-details-page/anime-details-page.component.html
> +		<a [routerLink]="['../create']" title="Anime create page" type="button" mat-raised-button>Create anime</a>
According to semantics, the type attribute should be the `<button>` tag, not the `<a>` tag

```suggestion
		<a [routerLink]="['../create']" title="Anime create page" mat-raised-button>Create anime</a>
```

2023-08-26 19:34 UTC, dmitrymaslov13 commented on apps/angular/src/app/features/anime/anime-details-page/anime-details-page.component.html
> +		<a routerLink="edit" mat-icon-button title="Anime edit page" type="button">
Also in here

2023-08-26 19:34 UTC, dmitrymaslov13 commented on apps/angular/src/app/features/anime/manage-anime/anime-edit-page/anime-edit-page.component.ts
> +		}));
I see that this method is duplicated in different classes.
I suggest you do something about it

2023-08-26 19:34 UTC, dmitrymaslov13 commented on apps/angular/src/app/features/anime/manage-anime/anime-form/anime-form.component.ts
> +				}),
Can we make this navigate in subscribe?

2023-08-26 19:34 UTC, dmitrymaslov13 commented on apps/angular/src/core/services/image.service.ts
> +	private getImageFormData(instructions: S3InstructionsDto, file: File): { url: string; formData: FormData; } {
Don't forget about `readonly`.

```suggestion
	private getImageFormData(instructions: S3InstructionsDto, file: File): Readonly<{ url: string; formData: FormData; }> {
```

2023-08-26 19:34 UTC, dmitrymaslov13 commented on apps/angular/src/shared/components/custom-form-select/custom-form-select.component.ts
> +	}
Ooh, this looks complicated. Let's move the subscriptions into separate methods that describe what we are subscribing to.

`subcribeToParamsChanges()`
`subcribeToInnerControlChanges()`

2023-08-26 19:34 UTC, dmitrymaslov13 commented on apps/angular/src/shared/components/custom-form-select/custom-form-select.component.ts
> +		}
Look, you can get your item without `querySelector`

Use [`@ViewChild()`](https://angular.io/api/core/ViewChild)

2023-08-26 19:34 UTC, dmitrymaslov13 commented on apps/angular/src/shared/components/custom-form-select/custom-form-select.component.ts
> +	public getAddedItem = new EventEmitter<DefaultParams>();
This name seems to be somewhat misleading too

2023-08-26 19:34 UTC, dmitrymaslov13 commented on apps/angular/src/shared/components/custom-form-select/custom-form-select.component.ts
> +	protected filteredItems$ = new BehaviorSubject<readonly T[]>([]);
```suggestion
	protected readonly filteredItems$ = new BehaviorSubject<readonly T[]>([]);
```

2023-08-27 10:02 UTC, dmitrymaslov13 commented on apps/angular/src/shared/components/custom-image-uploader/custom-image-uploader.component.html
> +		<button #innerButtonnn mat-icon-button type="button" (click)="triggerInput()"><mat-icon>insert_photo</mat-icon></button>
`#innerButtonnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn`

:DDDD

2023-08-27 10:03 UTC, EgorRyazanov commented on apps/angular/src/shared/components/custom-image-uploader/custom-image-uploader.component.html
> +		<button #innerButtonnn mat-icon-button type="button" (click)="triggerInput()"><mat-icon>insert_photo</mat-icon></button>
oopss ahaha

2023-08-28 06:14 UTC, merged